CREATE TABLE T_ENQUETE(
ID INT PRIMARY KEY,
NM_DESCRICAO VARCHAR(200) NOT NULL,
NU_VIEW INT DEFAULT 0
);

CREATE TABLE T_OPCAO(
ID_ENQUETE INT,
ID_OPCAO INT,
NM_OPCAO_DESCRICAO VARCHAR(100) NOT NULL,
NU_VOTO INTEGER NOT NULL,
CONSTRAINT FK_ENQUETE FOREIGN KEY (ID_ENQUETE) REFERENCES T_ENQUETE (ID) 
);

CREATE SEQUENCE SEQ_ENQUETE
INCREMENT BY 1
START WITH 1;